### PR TITLE
some more design considerations

### PR DESCRIPTION
**Pull request by manuelschiller**
I try to flesh out some ideas on how we might get this concurrency thing working. Feel free to tell me which ideas are good, and which ones are not. I expect to iterate on this as feedback trickles in (and my ideas become a little clearer)...

### CODE REVIEW

**Comment by GerhardRaven** [comment]
I like the direction this is going -- merged.

**Comment by betatim** [comment]
Gerhard commented here: https://github.com/lhcb/scheduling-event-model/commit/c03ba28affc0bdbf5a99680f94e5181ad9bbaed0 (just so we don't lose it)

**Comment by betatim** [comment]
Meta: we should keep PRs open for a bit to give people a chance to comment before merge

Post-merge discussion: I think we should abandon the concept of the TES. In a world where we express the computations as graphs you do not need it anymore.

One way of expressing a graph (using [dask's spec](http://dask.pydata.org/en/latest/spec.html))

``` python
{'x': 1,
 'y': 2,
 'z': (add, 'x', 'y'),
 'w': (sum, ['x', 'y', 'z'])}
```

which results in `w` being `x+y+z`, `z` is computed and `x` and `y` are inputs. `add` and `sum` are `Transform`s in our language, together with their inputs they form `Task`s (??). The need to store stuff in a global variable (with all the race conditions, locks, etc) goes away as you pass the output of one `Task` to the next.

One thing that is tricky with this approach is accumulating/batching events. Presumably you would have one graph that describes the whole processing for one event. You could make a graph which describes the processing of a whole batch of events ...

For Mailboxes/message passing we should investigate `erlang`. They have a very nice model for this. `0MQ` probably contains a lot of basic primitives to build upon as well.

I tihnk having to deal with locks and mutexes explicitly (or allowing me to send a message and wait for messages) is asking for deadlocks. The need for this (completely?) goes away if we can write things down in a 'functional programming' style.

**Comment by manuelschiller** [comment]
Tim, I agree that the TES seems somewhat outdated. OTOH, all our persisted data is built around that beast. Unless we feel we are superhuman, I think we ought to think twice if we can really afford to ditch that concept entirely, because it ultimately means we have to reinvent, or at least reimplement, the wheel for persistency.

Concerning the idea about pipes and mailboxes: This was seen through my kernel glasses. In the end this will need to be implemented in some high level framework, and locking and mutexes will be entirely hidden from the user. If we can get this working with just C++'s core (including the new threading support) plus maybe some judicious use of pthreads behind the scenes, I'd prefer we do that.

0MQ has a lot of flexibility built in that comes in handy when you eventually want processes to  commuicate across machine boundaries, but that's bound to cost something, and I am not convinced yet that we need that kind of flexibility in the general case (and brittleness that comes with it - at the moment, when a HLT node hangs for some reason, the capacity is somewhat dimished, but the system keeps going by and large; if different machines do different things, one node hanging of e.g. three doing Velo track reco can mean that suddenly a third of your VELO track reco is blocked, and the entire system will start to degrade severely...). OTOH, it's quite clear that sending off work units to the few machines equipped with FPGAs or GPUs or whatever other accelerator technologies we have until then would be a perfect use case for 0MQ. I just think for the general case where we hand data from thread to thread on the same machine it's overkill.

**Comment by GerhardRaven** [comment]
I think the TES can stay as a 'back end' for persistency, i.e. in a network of pipes, on the producer side, there is one final algorithm that requests as input all things that need persisting, and then writes them into the TES, and from then it is business as usual. Also one can insert small algorithms in the middle of the stream to populate the TES. Or be even mode fancy, and have a generic 'facade' turning a Transform into an Algorithm which does nothing than fetch input from the TES, invoke a Transform on it, and put the output back into the TES. And it can then also point the next 'facade' to its output -- so the TES becomes the 'backing store' where objects live after a Transform is done with them, i.e. the output buffer of Transforms.

**Pull request merged**
